// Auto-generated from config/action_registry.json — do not edit.
// Run: python3 ops/export_action_registry_ts.py

/** Map UI/API action name -> hostd action name. Single source: config/action_registry.json */
export const ACTION_TO_HOSTD: Record<string, string> = {
  "apply": "apply",
  "artifacts": "artifacts",
  "autopilot_disable": "autopilot_disable",
  "autopilot_enable": "autopilot_enable",
  "autopilot_install": "autopilot_install",
  "autopilot_run_now": "autopilot_run_now",
  "autopilot_status": "autopilot_status",
  "deploy_and_verify": "deploy_and_verify",
  "doctor": "doctor",
  "guard": "guard",
  "journal": "tail_guard_log",
  "llm.microgpt.canary": "llm.microgpt.canary",
  "llm_doctor": "llm_doctor",
  "openclaw_hq_audit": "openclaw_hq_audit",
  "openclaw_novnc_doctor": "openclaw_novnc_doctor",
  "openclaw_novnc_restart": "openclaw_novnc_restart",
  "openclaw_novnc_routing_fix": "openclaw_novnc_routing_fix",
  "openclaw_novnc_shm_fix": "openclaw_novnc_shm_fix",
  "orb.backtest.bulk": "orb.backtest.bulk",
  "orb.backtest.confirm_nt8": "orb.backtest.confirm_nt8",
  "playbook.reconcile_frontdoor_serve": "playbook.reconcile_frontdoor_serve",
  "playbook.recover_hq_routing": "playbook.recover_hq_routing",
  "playbook.recover_novnc_ws": "playbook.recover_novnc_ws",
  "port_audit": "port_audit",
  "ports": "port_audit",
  "pred_markets.mirror.backfill": "pred_markets.mirror.backfill",
  "pred_markets.mirror.run": "pred_markets.mirror.run",
  "pred_markets.report.daily": "pred_markets.report.daily",
  "pred_markets.report.health": "pred_markets.report.health",
  "sms_status": "sms_status",
  "soma_connectors_status": "soma_connectors_status",
  "soma_fix_and_retry": "soma_fix_and_retry",
  "soma_harvest": "soma_harvest",
  "soma_kajabi_auto_finish": "soma_kajabi_auto_finish",
  "soma_kajabi_bootstrap_finalize": "soma_kajabi_bootstrap_finalize",
  "soma_kajabi_bootstrap_start": "soma_kajabi_bootstrap_start",
  "soma_kajabi_bootstrap_status": "soma_kajabi_bootstrap_status",
  "soma_kajabi_capture_interactive": "soma_kajabi_capture_interactive",
  "soma_kajabi_discover": "soma_kajabi_discover",
  "soma_kajabi_gmail_connect_finalize": "soma_kajabi_gmail_connect_finalize",
  "soma_kajabi_gmail_connect_start": "soma_kajabi_gmail_connect_start",
  "soma_kajabi_gmail_connect_status": "soma_kajabi_gmail_connect_status",
  "soma_kajabi_phase0": "soma_kajabi_phase0",
  "soma_kajabi_reauth_and_resume": "soma_kajabi_reauth_and_resume",
  "soma_kajabi_session_check": "soma_kajabi_session_check",
  "soma_kajabi_session_warm_disable": "soma_kajabi_session_warm_disable",
  "soma_kajabi_session_warm_enable": "soma_kajabi_session_warm_enable",
  "soma_kajabi_session_warm_status": "soma_kajabi_session_warm_status",
  "soma_kajabi_snapshot_debug": "soma_kajabi_snapshot_debug",
  "soma_kajabi_unblock_and_run": "soma_kajabi_unblock_and_run",
  "soma_last_errors": "soma_last_errors",
  "soma_mirror": "soma_mirror",
  "soma_novnc_oneclick_recovery": "soma_novnc_oneclick_recovery",
  "soma_run_to_done": "soma_run_to_done",
  "soma_snapshot_home": "soma_snapshot_home",
  "soma_snapshot_practitioner": "soma_snapshot_practitioner",
  "soma_status": "soma_status",
  "soma_zane_finish_plan": "soma_zane_finish_plan",
  "system.reconcile": "system.reconcile",
  "system.state_pack": "system.state_pack",
  "tail_guard_log": "tail_guard_log",
  "timer": "timer",
};

/** Project ID -> set of allowlisted action ids for POST /api/projects/[projectId]/run */
export const PROJECT_ACTIONS: Record<string, ReadonlySet<string>> = {
  "soma_kajabi": new Set(["openclaw_novnc_restart", "soma_connectors_status", "soma_fix_and_retry", "soma_kajabi_auto_finish", "soma_kajabi_bootstrap_finalize", "soma_kajabi_bootstrap_start", "soma_kajabi_bootstrap_status", "soma_kajabi_capture_interactive", "soma_kajabi_discover", "soma_kajabi_gmail_connect_finalize", "soma_kajabi_gmail_connect_start", "soma_kajabi_gmail_connect_status", "soma_kajabi_reauth_and_resume", "soma_kajabi_session_check", "soma_kajabi_session_warm_disable", "soma_kajabi_session_warm_enable", "soma_kajabi_session_warm_status", "soma_kajabi_snapshot_debug", "soma_kajabi_unblock_and_run", "soma_novnc_oneclick_recovery", "soma_run_to_done", "soma_zane_finish_plan"]),
};

