#!/usr/bin/env bash
# openclaw_fix_ssh_tailscale_only.sh — Lock sshd to Tailscale IP only.
#
# Intended to run as root on the VPS (aiops-1).
# Fail-closed: exits non-zero if ANY step fails.
#
# What it does:
#   1. Determines the Tailscale IPv4 address.
#   2. Disables ssh.socket if active (systemd socket activation bypasses sshd_config).
#   3. Writes /etc/ssh/sshd_config.d/99-tailscale-only.conf:
#        AddressFamily inet
#        ListenAddress <TAILSCALE_IP>
#   4. Validates the config with: sshd -t
#   5. Restarts sshd: systemctl restart ssh
#   6. Verifies with: ss -ltnp | grep :22 that sshd no longer on 0.0.0.0 / :::
#
# Test mode: set OPENCLAW_TEST_ROOT to a temp dir to run without root
#            (stubs systemctl/tailscale/sshd/ss in PATH).
#
# Does NOT change auth methods, disable root login, or alter any other
# sshd settings. Minimal and safe.
#
# Usage:
#   sudo ./ops/openclaw_fix_ssh_tailscale_only.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "=== openclaw_fix_ssh_tailscale_only.sh ==="
echo "  Time: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "  Host: $(hostname)"
echo ""

# --- 0. Root check (skipped in test mode) ---
OPENCLAW_TEST_ROOT="${OPENCLAW_TEST_ROOT:-}"
if [ -n "$OPENCLAW_TEST_ROOT" ]; then
  echo "  [TEST MODE] OPENCLAW_TEST_ROOT=$OPENCLAW_TEST_ROOT"
fi
if [ -z "$OPENCLAW_TEST_ROOT" ] && [ "$(id -u)" -ne 0 ]; then
  echo "ERROR: This script must run as root (use sudo)." >&2
  exit 1
fi

# --- 1. Determine Tailscale IPv4 ---
echo "--- Step 1: Determine Tailscale IPv4 ---"
if ! command -v tailscale >/dev/null 2>&1; then
  echo "ERROR: tailscale command not found. Is Tailscale installed?" >&2
  exit 1
fi

TS_IP="$(tailscale ip -4 2>/dev/null | head -n1 | tr -d '[:space:]')"
if [ -z "$TS_IP" ]; then
  echo "ERROR: Could not determine Tailscale IPv4 address." >&2
  echo "  Is Tailscale up? Run: tailscale status" >&2
  exit 1
fi

# Validate it looks like a tailnet IP (100.64.0.0/10)
if ! echo "$TS_IP" | grep -qE '^100\.(6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])\.'; then
  echo "ERROR: Tailscale IP '$TS_IP' is not in the expected 100.64.0.0/10 range." >&2
  exit 1
fi

echo "  Tailscale IPv4: $TS_IP"

# --- 2. Disable ssh.socket (systemd socket activation) ---
echo ""
echo "--- Step 2: Handle ssh.socket (systemd socket activation) ---"
# When ssh.socket is active, systemd binds :22 on 0.0.0.0/[::] directly and
# ignores sshd_config ListenAddress directives entirely.  We must disable it.
if systemctl list-unit-files 2>/dev/null | grep -q '^ssh\.socket'; then
  echo "  ssh.socket unit found — disabling socket activation"
  systemctl disable --now ssh.socket 2>/dev/null || true
  systemctl stop ssh.socket 2>/dev/null || true
  # Mask prevents systemd from re-enabling on package upgrades
  systemctl mask ssh.socket 2>/dev/null || true
  echo "  ssh.socket: disabled + masked"
  # Ensure the traditional ssh/sshd service is enabled (not socket-activated)
  if systemctl list-unit-files ssh.service 2>/dev/null | grep -q 'ssh\.service'; then
    systemctl enable ssh.service 2>/dev/null || true
    echo "  ssh.service: enabled"
  elif systemctl list-unit-files sshd.service 2>/dev/null | grep -q 'sshd\.service'; then
    systemctl enable sshd.service 2>/dev/null || true
    echo "  sshd.service: enabled"
  fi
else
  echo "  ssh.socket not present — no action needed"
fi

# --- 3. Write sshd drop-in config ---
echo ""
echo "--- Step 3: Write sshd config ---"
SSHD_CONF_DIR="${OPENCLAW_TEST_ROOT}/etc/ssh/sshd_config.d"
SSHD_CONF="$SSHD_CONF_DIR/99-tailscale-only.conf"

if [ ! -d "$SSHD_CONF_DIR" ]; then
  echo "  Creating $SSHD_CONF_DIR"
  mkdir -p "$SSHD_CONF_DIR"
fi

cat > "$SSHD_CONF" <<EOF
# Generated by openclaw_fix_ssh_tailscale_only.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Lock sshd to Tailscale interface only (no public exposure).
# Do NOT edit manually; re-run the script to update.
AddressFamily inet
ListenAddress $TS_IP
EOF

chmod 644 "$SSHD_CONF"
echo "  Written: $SSHD_CONF"
echo "    AddressFamily inet"
echo "    ListenAddress $TS_IP"

# --- 4. Validate sshd config ---
echo ""
echo "--- Step 4: Validate sshd config ---"
if ! sshd -t 2>&1; then
  echo "ERROR: sshd config validation failed (sshd -t). Removing drop-in." >&2
  rm -f "$SSHD_CONF"
  echo "  Removed $SSHD_CONF to restore previous config." >&2
  exit 1
fi
echo "  sshd -t: OK"

# --- 5. Restart sshd ---
echo ""
echo "--- Step 5: Restart sshd ---"
if ! systemctl restart ssh 2>&1 && ! systemctl restart sshd 2>&1; then
  echo "ERROR: Failed to restart sshd." >&2
  echo "  Removing drop-in to restore previous config." >&2
  rm -f "$SSHD_CONF"
  # Try to restart with original config
  systemctl restart ssh 2>/dev/null || systemctl restart sshd 2>/dev/null || true
  exit 1
fi
echo "  sshd restarted"

# --- 6. Verify ---
echo ""
echo "--- Step 6: Verify ---"
# Give sshd a moment to bind
sleep 1

if command -v ss >/dev/null 2>&1; then
  SSH_BINDS="$(ss -ltnp 2>/dev/null | grep ':22 ' || true)"
  echo "  Current :22 listeners:"
  echo "$SSH_BINDS" | while IFS= read -r line; do
    [ -n "$line" ] && echo "    $line"
  done

  # Check for public binds (0.0.0.0:22, [::]:22, *:22)
  if echo "$SSH_BINDS" | grep -qE '0\.0\.0\.0:22|\[::\]:22|\*:22'; then
    echo "" >&2
    echo "ERROR: sshd is STILL bound to a public address after fix!" >&2
    echo "" >&2
    echo "  --- Debug: sshd effective config ---" >&2
    sshd -T 2>&1 | grep -iE 'addressfamily|listenaddress|port' >&2 || true
    echo "  --- Debug: systemctl status ---" >&2
    systemctl status ssh.socket ssh.service sshd.service 2>&1 | head -30 >&2 || true
    echo "  --- Debug: sshd config files ---" >&2
    grep -rnH 'ListenAddress\|AddressFamily\|Include' \
      "${OPENCLAW_TEST_ROOT}/etc/ssh/sshd_config" \
      "${OPENCLAW_TEST_ROOT}/etc/ssh/sshd_config.d/" 2>/dev/null >&2 || true
    echo "" >&2
    echo "  Possible causes:" >&2
    echo "    - ssh.socket re-activated (check: systemctl is-active ssh.socket)" >&2
    echo "    - Conflicting ListenAddress in /etc/ssh/sshd_config" >&2
    echo "    - Include directive loading configs before our drop-in" >&2
    exit 1
  fi

  # Confirm bound to tailscale IP
  if echo "$SSH_BINDS" | grep -q "$TS_IP:22"; then
    echo ""
    echo "  VERIFIED: sshd is now bound to $TS_IP:22 only."
  else
    echo "" >&2
    echo "WARNING: sshd does not appear bound to $TS_IP:22." >&2
    echo "  Check the output above. It may be bound to another Tailscale IP." >&2
    # Don't fail — it might be on a different tailnet IP if multi-homed
  fi
else
  echo "  ss not available — skipping verification (run openclaw_doctor.sh to confirm)"
fi

echo ""
echo "=== sshd is now Tailscale-only ==="
echo "  ListenAddress: $TS_IP"
echo "  Config file:   $SSHD_CONF"
echo ""
echo "  Run ./ops/openclaw_doctor.sh to confirm all checks pass."
exit 0
